class ScanReportConstants:
    ID = "id"
    TYPE = "type"
    VERSION = "version"
    USER = "user"
    DATE = "date"
    TIME = "time"
    ROOT_DIR = "root_dir"
    IP_ADDRESS_LIST = "ip_address_list"
    REPORT_PATHS_LIST = "image_result_list"
    SCAN_SOFTWARE = "scan_software"
    BLACKDUCK = "BLACKDUCK"
    TWISTLOCK = "TWISTLOCK"
    REMOTE_HOST = "REMOTE_HOST"
    ARTIFACTORY = "ARTIFACTORY"
    LOCAL_IMAGE = "LOCAL_IMAGE" 
    KUBERNETES: str = "KUBERNETES"