class TwistlockReportParserConstants:
    DATE_TIME_FORMAT = "%Y-%m-%dT%H:%M:%SZ"
    SECRETS = "Secrets"
    OSDISTRO = "osDistro"
    OSDISTROVERSION = "osDistroVersion"
    OSDISTRORELEASE = "osDistroRelease"
    DISTRO = "distro"
    PACKAGES = "packages"
    APPLICATIONS = "applications"
    ID = "id"
    COMPLIANCEISSUES = "complianceIssues"
    COMPLIANCES = "compliances"
    VULNERABILITIES = "vulnerabilities"
    REPOTAG = "repoTag"
    TAGS = "tags"
    NAMESPACES = "namespaces"
    PKGS = "pkgs"
    PKGSTYPE = "pkgsType"