class WebAppConstants:
    SCAN_ID = "scan_id"
    IMAGE_ID = "image_id"
    CVE_ID = "cve_id"
    JIRAS = "jiras"
    JIRA_STATUS = "jira_status"
    JIRA_SUMMARY = "jira_summary"
    PACKAGE_NAME = "pkgName"
    VERSION = "version"
    CVE = "cve"
    JIRA_LIST = "jira_list"
    PATH_LIST = "path_list"
    PACKAGE_VERSION = "pkgVersion"
    IS_REMOVAL = "isRemoval"
    PAGE_NAME = "page_name"