class TwistlockProjectConfig:
    LOCAL_IMAGE_TWISTLOCK = "LOCAL_IMAGE_TWISTLOCK"
    REMOTE_IMAGE_TWISTLOCK = "REMOTE_IMAGE_TWISTLOCK"
    ARTIFACTORY_TWISTLOCK = "ARTIFACTORY_TWISTLOCK"
    KUBERNETES_TWISTLOCK = "KUBERNETES_TWISTLOCK"
    
    PROJECT_TYPES = [
        LOCAL_IMAGE_TWISTLOCK,
        REMOTE_IMAGE_TWISTLOCK,
        ARTIFACTORY_TWISTLOCK,
        KUBERNETES_TWISTLOCK
    ]